blog/urls.py
from django.urls import path
from .views import ArticleListView,ArticleDetailView,ArticleCreateView,ArticleUpdateView,ArticleDeleteView,HomeView
urlpatterns=[
    path('',ArticleListView.as_view(),name='home'),
    path('home',HomeView.as_view(),name='homeview'),
    path('<int:id>',ArticleDetailView.as_view(),name='detail'),
    path('create',ArticleCreateView.as_view(),name='create'),
    path('<int:pk>/update',ArticleUpdateView.as_view(),name='update'),
    path('<int:id>/delete',ArticleDeleteView.as_view(),name='delete')
]

second/urls.py
from django.urls import path
from .views import index,task,register,home,movie_details,movie_delete
app_name='second'
urlpatterns=[
    path("",home,name='home'),
    path("home",index,name="index"),
    path('task', task, name='task'),
    path('register',register, name='register'),
    path('detail',movie_details, name='movie'),
    path('detail/<int:my_id>/',movie_details,name='detail'),
    path('detail/<int:my_id>/delete',movie_delete,name='delete')
]

web_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first.urls')),
    path('second/',include('second.urls')),
    path('blog/',include('blog.urls')),
    path('movie/',include('movie.urls'))
]

second/models.py
from django.db import models
import datetime
from django.urls import reverse
class Movie(models.Model):
    name=models.CharField(max_length=50)
    release_year=models.CharField(max_length=10)
    director=models.CharField(max_length=50)
    actor=models.CharField(max_length=50)
    def __str__(self):
        return self.name+' '+self.release_year+" "+self.director+' '+self.actor
    def get_absolute_url(self):
        return reverse("second:detail",kwargs={"my_id":self.id})


class User(models.Model):
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    date_created=models.DateTimeField(auto_now=True)
    email=models.EmailField(max_length=30)
    password=models.CharField(max_length=20)
    birthday=models.DateField()
    age=models.DecimalField(max_digits=3, decimal_places=0)
    CheckedIn=models.BooleanField(null=False,blank=False)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

second/forms.py
from django import forms
from django.forms import ModelForm
from .models import Movie,User
FAVORITE_COLORS_CHOICES = [
    ('blue', 'Blue'),
    ('green', 'Green'),
    ('black', 'Black'),
]
BIRTH_YEAR_CHOICES = ['1980', '1981', '1982']
CHOICES = [('1', 'First'), ('2', 'Second'),('3','Third')]
class MovieForm(ModelForm):
    class Meta:
        model=Movie
        fields="__all__"
class Task(forms.Form):
    name=forms.CharField(label='Task',max_length=100,widget=forms.TextInput(attrs={'id':'New','class':'form'}))
    favorite_colors = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class':'form'}),
        choices=FAVORITE_COLORS_CHOICES,
    )
    birth_year = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES))
    choice_field = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class':'form'}), choices=CHOICES)
    birth_year.widget.attrs.update({'class':'form'})
    def clean_name(self):
        name=self.cleaned_data.get("name")
        if not "play" in name:
            raise forms.ValidationError("Please include play")
        else:
            return name
class UserForm(ModelForm):
    class Meta:
        model=User
        fields="__all__"

second/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Movie,User
from .forms import MovieForm,Task,UserForm
from django.http import HttpResponse
task_name=[]
def home(request):
    return render (request, 'second/navbar.html')

def index(request):
    objs=Movie.objects.all()
    if request.method=='POST':
        form=MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/second/home')
    else:
        form=MovieForm()
    return render(request,'second/index.html',{'form': form,'objs':objs})
def task(request):
    if request.method=="POST":
        form=Task(request.POST)
        if form.is_valid():
            tasks=form.cleaned_data['name']
            task_name.append(tasks)
    else:
        form=Task()
    return render(request,'second/task.html',{'form':form,'task_name':task_name})
def register(request):
    if request.method=="POST":
        form=UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/second/register')
    else:
        form=UserForm()
    return render(request,'second/register.html',{'form':form})
def movie_details(request,my_id=1):
    #movie=Movie.objects.get(id=my_id)
    movie=get_object_or_404(Movie,id=my_id)
    context={
        "objects":movie
    }
    return render(request,'second/detail.html',context)
def movie_delete(request,my_id=1):
    movie=Movie.objects.get(id=my_id)
    context={
        "objects":movie
    }
    if request.method=="POST":
        movie.delete()
        return redirect('../../')
    return render (request,'second/delete.html',context)
# Create your views here.

second/templates/second/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%}</title>
    {% block static %} {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    {% include 'second/navbar.html' %}
    {% block content %}

    {% endblock %}
</body>
</html>

second/templates/second/delete.html
{% extends 'second/base.html' %}
{% block title%} detail {% endblock%}
{% block content %}
<form method="POST" action="{% url 'second:delete' objects.id %}">
    {% csrf_token %}
<h1>Do you want to delete this {{objects.name}} ?</h1>
<button type="submit">Yes</button>
</form>
<br>
<button onclick=window.location.href="{% url 'second:index' %}">Cancel</button>
{% endblock %}

second/templates/second/detail.html
{% extends 'second/base.html' %}
{% block title%} detail {% endblock%}
{% block content %}
<h1>{{objects.name}}</h1>
<p>Released year: {{objects.release_year}}</p>
<p>Director: {{objects.director}}</p>
<p>Actor: {{objects.actor}}</p>
{% endblock %}

second/templates/second/index.html
{% extends 'second/base.html' %}
    {% block title %}Document {% endblock %}
    {% block static%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'second/style.css' %}">
    {% endblock %}
    {% block content %}
    <h1> Movie</h1>
    <form action='{% url 'second:index' %}' method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <br>
    <br>
    <h1>All Movies</h1>
    <table style="width:100%;">
        <tr>
            <th>Name</th>
            <th>Release year</th>
            <th>Director</th>
            <th>Actor</th>
            <th>Action</th>
        </tr>
        {% for obj in objs%}
            <tr>
                <th><a href="{{obj.get_absolute_url}}">{{obj.name}}</a></th>
                <th>{{obj.release_year}}</th>
                <th>{{obj.director}}</th>
                <th>{{obj.actor}}</th>
                <th><a href="{% url 'second:delete' obj.id %}">Delete</a></th>
            </tr>
        {% endfor %}
    </table>
    {% endblock %}

second/templates/second/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'second:index'%}">Home</a></li>
        <li><a href="{% url 'second:register' %}">Register</a></li>
        <li><a href="{% url 'second:task' %}">Task</a></li>
    </ul>
</nav>

second/templates/second/register.html
{% extends 'second/base.html' %}
{% block title %}Register {% endblock %}
    {% block content %}
    <h1>Register Here</h1>
    <form method="POST" action="/second/register">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Register</button>
    </form>
    {% endblock %}

second/templates/second/task.html
{% extends 'second/base.html' %}
{% block title %} Task {% endblock %}
{% block content%}
        <h1> Task</h1>
        {% if task_name %}
        <ul>
        {% for task in task_name %}
            <li><a>{{ task }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No task is available.</p>
        {% endif %}
        <form action='{% url 'second:task' %}' method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Add Task</button>
        </form>
{% endblock %}